name: KeepAlive Ping

on:
  schedule:
    - cron: "* * * * *"   # har 1 minute trigger
  workflow_dispatch:      # manually run karne ka option

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'   # stable version

      - name: Install dependencies
        run: pip install requests

      - name: Run ping script
        run: python ping_once.py   # yahan naam change
